### ISSUE TITLE
Downloading several files in batch

### ISSUE THREAD

**Issue by zzynx** [kennethjiang/js-file-download#60]
I try to use this library in my React PWA for downloading a bunch of files like this: The user 
1. selects a number of items in a list and 2. presses an export button

The piece of typescript code that I use is this:
```typescript
    confirmExport = () => {
        const fileDownload = require('js-file-download');
        for (const att of this.props.attesten) {
            if (this.state.selectedAttestIds.includes(att.id)) {
                fileDownload(att.certificate, `certificate_${att.id}.xml`);
            }
        }
    };
```
I experience that if the user eg. selects 20 items, the result is only 10 or 15 downloaded xml files.
If I add logging for each file, I see that each of the 20 files is mentioned, however some of them are apparently NOT downloaded. (and yes, their names are unique. It's not that one file overwrites another)
If I change the settings of Chrome to ask me where to save a file, it opens a popup for each of the 20 files and each of them is downloaded correctly. If I change the setting back to "Don't ask me where to save" I have the problem again.
This makes me think of some kind of race condition...
Any ideas?

**Comment by motevets** [comment]
Thanks for your bug report. I was able to reproduce this issue, but after some research, it appears that this is an intended (or at least commonly observed) behaviour of Chrome and not a bug in js-file-download. See https://stackoverflow.com/a/54200538.

It's not clear what exactly is causing this, but if I had to guess, I'd say it's because [Chrome doesn't allow more than six concurrent downloads](https://bugs.chromium.org/p/chromium/issues/detail?id=12066), which is why the number of downloads you end up getting to go through changes from time to time and why when you modify your settings to ask you to confirm the download, the issue goes away. (You're giving time for your previous download to finish.)

Two ideas on how you could work around this issue:
1. Compress your files into one zip file, either server-side or in Javascript using something like [zip.js](https://gildas-lormeau.github.io/zip.js/).
2. Use `setInterval` or `setTimeout` to put a little time in between your downloads. It shouldn't need to be very long, say a few hundred milliseconds, because Chrome isn't actually downloading the file, just saving it.

Good luck!
